### ISSUE TITLE
Could you please introduce the architecure of your demo

### ISSUE THREAD

**Issue by TomHuangsrc** [yhqiu16/NVMeCHA#12]
Hi Guy,
   From your paper, I cannot find where the NVME  SSD connected.  From the top file, I only find x8 pcie signal connect to host, right?
   Which singls are used for connecting NVME SSD?
   
    For my guess, the demo should one port connect to host through pcie XDMA, and one port connect to NVME SSD, right?

    Looking forward to your feedback.

Tom

**Comment by yhqiu16** [comment]
This is a NVMe controller supporting the NVMe protocol but not connected to the backend storage media such as NAND Flash.

**Comment by TomHuangsrc** [comment]
Thanks for your reply.
Your controller is not connected to NVME directly, and your controller should be one part of NVME SSD which repond to the NVME command from host and then control the write/read action to NAND flash, rigfht?
Tom

**Comment by TomHuangsrc** [comment]
your controller could connect to host directly, and the host would take your controller as a NVME device, right?
Thanks a lot.
Tom

**Comment by yhqiu16** [comment]
Yes, you are right. But notice that the FTL is not integrated with our NVMe controller yet.
