### ISSUE TITLE
Is it necessary to use vitis to burn the program on the board?

### ISSUE THREAD

**Issue by preta21** [yhqiu16/NVMeCHA#2]
Hello, I'm trying to use the NVMeCHA in my FPGA board (with an arm processor), using **VIVADO 2019.2** and having burned the bin file on my board, but something went wrong when I processed the SPDK's hello_world sample. I suspect that maybe the firmware codes weren't burned correctly, or need **VITIS**?

I checked out that the board KCU105 you used is a PL BOARD (without a processor), which works without the use of vitis.
However, you mentioned Vitis2019.2 in the README  in the mainpage of the NVMeCHA on GitHub. 
So, sincerely, I wonder whether it's necessary to use **VITIS 2019.2** to have the whole program burned correctly.
Thank you.

**Comment by yhqiu16** [comment]
The firmware should run on a processor, which is the MicroBlaze soft-core IP in our project. VITIS is used to build the software code and program the FPGA.
The working flow is: 1) build the hardware project in Vivado and export hardware; 2) launch VITIS and build the software; 3) power on the FPGA board and program FPGA using VITIS; 4) power on the host computer and test.

**Comment by preta21** [comment]
I'm sorry to make a  late response.
Really thank you very much, I'll keep trying about it.

**Comment by preta21** [comment]
After programming the fw codes on my board using vitis, I think the NVMeCHA works well with SPDK now.
Bravo! Thanks again!

**Comment by yhqiu16** [comment]
Great! You are welcome!
