### ISSUE TITLE
A potential mistake in the Publication article: it's the CONTROLLER who inverts the P phase tag 

### ISSUE THREAD

**Issue by preta21** [yhqiu16/NVMeCHA#3]
Hello!
Sincerely I'm a fan of your work NMVeCHA.
Taking notes of the publication "A High-Performance and Scalable NVMe Controller Featuring Hardware Acceleration", at the same time, I'm  making some surveys on [NVMe1.4](https://nvmexpress.org/wp-content/uploads/NVM-Express-1_4-2019.06.10-Ratified.pdf), which is the first one in the article's renference list.
When learning about the mechanism of P phase tag, I might find something different between the article's PART II and the 7.2.1 in NVMe1.4.
In part II, you mentioned "**The HOST processes the new CQ entry and inverts the phase tag**" in the 7th step of NVMe command processing; 
however, in the 7.2.1 of the express specification, where it describes the details of command processing officially, the document says "After a command has completed execution, the controller places a completion queue entry in the next free slot in the associated Completion Queue. As part of the completion queue entry, the controller indicates the most recent Submission Queue entry that has been consumed by advancing the Submission Queue Head pointer in the completion entry. **Each new completion queue entry has a Phase Tag inverted from the previous entry to indicate to the host that this completion queue entry is a new entry**" , which is the 5th step of the process. I think this step is completed by CONTROLLER, as described above. Moreover, in the Figure123(Completion Queue entry), P phase tag 's introduction tells us "**Identifies whether a Completion Queue entry is new. The Phase Tag values for all Completion Queue entries shall be initialized to ‘0’ by host software prior to setting CC.EN to ‘1’. When the controller places an entry in the Completion Queue, the controller shall invert the Phase Tag to enable host software to discriminate a new entry**", which means CONTROLLER inverts the phase tag of a CQ entry, while the HOST is responsible for initializing a CQ entry.

So, will it be a potential detail mistake of the publication? 
I'm so sorry if it's me who misunderstanded the NVMe protocol.
Sincerely, thank you.

**Comment by yhqiu16** [comment]
Yes,  the sentence: "The HOST processes the new CQ entry and inverts the phase tag" is misleading. Thanks for your correction. 
The phase tag is inverted by the controller, as implemented in our controller. When introducing the CQE Submit module in Section IV, we describe the management of the phase tag: "The phase tag is managed internally, inverted every round of HCQ."

**Comment by preta21** [comment]
Got it, thank you!
