### ISSUE TITLE
UART16550 appears Garbled codes

### ISSUE THREAD

**Issue by preta21** [yhqiu16/NVMeCHA#5]
Hello, I'm running the NVMeCHA and wanna get some info from the uart, while got a lot of garbled codeds.
I confirmed that the uart module used with MicroBlaze is axi_uart16550 which has a default buad rate of 9600.
And I found the baud rate conf that you set is 9600 in the fw file `platform.c`.
However, when I tryed to grab some info from the **uart(PL Uart)**, whether on Win or Ubuntu, I always got something unreadable below.
![image](https://user-images.githubusercontent.com/44551638/197440447-1dcfa5f9-cb96-4994-b5bc-f96641eda995.png)

So is there sth wrong with my steps?
I guess I need another buad rate, or do other configurations?

**Comment by preta21** [comment]
I noticed some prints remained with Xilinx func `xil_printf()`, so I tryed to output them.

**Comment by yhqiu16** [comment]
There are two UART ports. One is used by the MicroBlaze with a baud rate of 9600. The other one is used by the zynq chip in the board with a baud rate of 115200. You can try different ports with different baud rates, and select the correct configuration.

**Comment by preta21** [comment]
> Hello, I'm running the NVMeCHA and wanna get some info from the uart, while got a lot of garbled codeds. I confirmed that the uart module used with MicroBlaze is axi_uart16550 which has a default buad rate of 9600. And I found the baud rate conf that you set is 9600 in the fw file `platform.c`. However, when I tryed to grab some info from the **uart(PL Uart)**, whether on Win or Ubuntu, I always got something unreadable below. ![image](https://user-images.githubusercontent.com/44551638/197440447-1dcfa5f9-cb96-4994-b5bc-f96641eda995.png)
> 
> So is there sth wrong with my steps? I guess I need another buad rate, or do other configurations?



> There are two UART ports. One is used by the MicroBlaze with a baud rate of 9600. The other one is used by the zynq chip in the board with a baud rate of 115200. You can try different ports with different baud rates, and select the correct configuration.

Oh I think the  problem probably occurs in my new PL design.
I just test the uart outputs using the orginal NVMeCHA, and it seemed normal.
Thanks a lot!

**Comment by preta21** [comment]
I changed the clock input module in the Block Design, which had affects on the output of UART's buad rate, thus got garbled codes. I recovered the clock design and the outputs are correct now.
